######################################################################
##
## Filename: decoder_top_tb.fdo
## Created on: Sun Jan 10 14:52:52 China Standard Time 2016
##
##  Auto generated by Project Navigator for Behavioral Simulation
##
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##  You may want to add additional commands to control the simulation
##  in the user specific do file (<module>.udo) which is automatically
##  generated in the project directory and will not be removed on
##  subsequent simulation flows run from Project Navigator.
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##
######################################################################
#
# Create work library
#
vdel -all
vlib work
#
# Compile sources
#
vlog  "../encoder/ipcore_dir/mul_12bits.v"
vlog  "best_d.v"
vlog  "ipcore_dir/fifo_11_to_11.v"
vlog  "decoder_main.v"
vlog  "decoder_top.v"
vlog  "decoder_top_tb.v"
vlog  "C:/Xilinx/13.2/ISE_DS/ISE//verilog/src/glbl.v"
#
# Call vsim to invoke simulator
#
vsim -voptargs="+acc" -t 1ps  -L xilinxcorelib_ver -L unisims_ver -L secureip -lib work work.decoder_top_tb glbl
#
# Source the wave do file
#
#do {decoder_top_tb_wave.fdo}
#
# Set the window types
#
#view wave
#view structure
#view signals
#
# Source the user do file
#
#do {decoder_top_tb.udo}
#
# Run simulation for this time
#
run 1000ns
#
# End
#
