######################################################################
##
## Filename: encoder_main.udo
## Created on: Wed Jan 13 17:53:35 China Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
