######################################################################
##
## Filename: encoder_main_tb.udo
## Created on: Tue Dec 29 10:28:53 China Standard Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
