######################################################################
##
## Filename: encoder_top_tb.udo
## Created on: Mon Jan 04 15:10:28 China Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
