onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /encoder_top_tb/i
add wave -noupdate /encoder_top_tb/bin_msg
add wave -noupdate /encoder_top_tb/clk
add wave -noupdate /encoder_top_tb/rst_b
add wave -noupdate /encoder_top_tb/start
add wave -noupdate /encoder_top_tb/msg_bype
add wave -noupdate /encoder_top_tb/wr_en
add wave -noupdate /encoder_top_tb/cw_out
add wave -noupdate /encoder_top_tb/cw_rdy
add wave -noupdate /encoder_top_tb/cw_done
add wave -noupdate /glbl/GSR
add wave -noupdate /encoder_top_tb/i
add wave -noupdate /encoder_top_tb/bin_msg
add wave -noupdate /encoder_top_tb/clk
add wave -noupdate /encoder_top_tb/rst_b
add wave -noupdate /encoder_top_tb/start
add wave -noupdate /encoder_top_tb/msg_bype
add wave -noupdate /encoder_top_tb/wr_en
add wave -noupdate /encoder_top_tb/cw_out
add wave -noupdate /encoder_top_tb/cw_rdy
add wave -noupdate /encoder_top_tb/cw_done
add wave -noupdate /glbl/GSR
add wave -noupdate /encoder_top_tb/i
add wave -noupdate /encoder_top_tb/bin_msg
add wave -noupdate /encoder_top_tb/clk
add wave -noupdate /encoder_top_tb/rst_b
add wave -noupdate /encoder_top_tb/start
add wave -noupdate /encoder_top_tb/msg_bype
add wave -noupdate /encoder_top_tb/wr_en
add wave -noupdate /encoder_top_tb/cw_out
add wave -noupdate /encoder_top_tb/cw_rdy
add wave -noupdate /encoder_top_tb/cw_done
add wave -noupdate /glbl/GSR
add wave -noupdate /encoder_top_tb/i
add wave -noupdate /encoder_top_tb/bin_msg
add wave -noupdate /encoder_top_tb/clk
add wave -noupdate /encoder_top_tb/rst_b
add wave -noupdate /encoder_top_tb/start
add wave -noupdate /encoder_top_tb/msg_bype
add wave -noupdate /encoder_top_tb/wr_en
add wave -noupdate /encoder_top_tb/cw_out
add wave -noupdate /encoder_top_tb/cw_rdy
add wave -noupdate /encoder_top_tb/cw_done
add wave -noupdate /glbl/GSR
add wave -noupdate /encoder_top_tb/i
add wave -noupdate /encoder_top_tb/bin_msg
add wave -noupdate /encoder_top_tb/clk
add wave -noupdate /encoder_top_tb/rst_b
add wave -noupdate /encoder_top_tb/start
add wave -noupdate /encoder_top_tb/msg_bype
add wave -noupdate /encoder_top_tb/wr_en
add wave -noupdate /encoder_top_tb/cw_out
add wave -noupdate /encoder_top_tb/cw_rdy
add wave -noupdate /encoder_top_tb/cw_done
add wave -noupdate /glbl/GSR
add wave -noupdate /encoder_top_tb/uut/clk
add wave -noupdate /encoder_top_tb/uut/rst_b
add wave -noupdate /encoder_top_tb/uut/start
add wave -noupdate /encoder_top_tb/uut/msg_bype
add wave -noupdate /encoder_top_tb/uut/wr_en
add wave -noupdate /encoder_top_tb/uut/cw_out
add wave -noupdate /encoder_top_tb/uut/cw_rdy
add wave -noupdate /encoder_top_tb/uut/cw_done
add wave -noupdate /encoder_top_tb/uut/dout
add wave -noupdate /encoder_top_tb/uut/rd_en
add wave -noupdate /encoder_top_tb/uut/full
add wave -noupdate /encoder_top_tb/uut/empty
add wave -noupdate /encoder_top_tb/uut/rd_data_count
add wave -noupdate /encoder_top_tb/uut/wr_data_count
add wave -noupdate /encoder_top_tb/uut/fifo/rst
add wave -noupdate /encoder_top_tb/uut/fifo/wr_clk
add wave -noupdate /encoder_top_tb/uut/fifo/rd_clk
add wave -noupdate /encoder_top_tb/uut/fifo/din
add wave -noupdate /encoder_top_tb/uut/fifo/wr_en
add wave -noupdate /encoder_top_tb/uut/fifo/rd_en
add wave -noupdate /encoder_top_tb/uut/fifo/dout
add wave -noupdate /encoder_top_tb/uut/fifo/full
add wave -noupdate /encoder_top_tb/uut/fifo/empty
add wave -noupdate /encoder_top_tb/uut/fifo/rd_data_count
add wave -noupdate /encoder_top_tb/uut/fifo/wr_data_count
add wave -noupdate /encoder_top_tb/uut/fifo/inst/BACKUP
add wave -noupdate /encoder_top_tb/uut/fifo/inst/BACKUP_MARKER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/CLK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/RST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/SRST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/WR_CLK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/WR_RST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/RD_CLK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/RD_RST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/DIN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/WR_EN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/RD_EN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/PROG_EMPTY_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/PROG_EMPTY_THRESH_ASSERT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/PROG_EMPTY_THRESH_NEGATE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/PROG_FULL_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/PROG_FULL_THRESH_ASSERT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/PROG_FULL_THRESH_NEGATE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/INT_CLK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/INJECTDBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/INJECTSBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/DOUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/FULL
add wave -noupdate /encoder_top_tb/uut/fifo/inst/ALMOST_FULL
add wave -noupdate /encoder_top_tb/uut/fifo/inst/WR_ACK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/OVERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/EMPTY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/ALMOST_EMPTY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/VALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/UNDERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/RD_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/WR_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/PROG_FULL
add wave -noupdate /encoder_top_tb/uut/fifo/inst/PROG_EMPTY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/SBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/DBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_ACLK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_ACLK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_ARESETN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_ACLK_EN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_ACLK_EN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWADDR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWLEN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWSIZE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWBURST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWLOCK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWCACHE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWPROT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWQOS
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWREGION
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWUSER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWVALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_AWREADY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_WID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_WDATA
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_WSTRB
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_WLAST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_WUSER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_WVALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_WREADY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_BID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_BRESP
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_BUSER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_BVALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_BREADY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWADDR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWLEN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWSIZE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWBURST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWLOCK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWCACHE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWPROT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWQOS
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWREGION
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWUSER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWVALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_AWREADY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_WID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_WDATA
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_WSTRB
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_WLAST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_WUSER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_WVALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_WREADY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_BID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_BRESP
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_BUSER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_BVALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_BREADY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARADDR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARLEN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARSIZE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARBURST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARLOCK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARCACHE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARPROT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARQOS
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARREGION
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARUSER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARVALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_ARREADY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_RID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_RDATA
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_RRESP
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_RLAST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_RUSER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_RVALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXI_RREADY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARADDR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARLEN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARSIZE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARBURST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARLOCK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARCACHE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARPROT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARQOS
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARREGION
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARUSER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARVALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_ARREADY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_RID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_RDATA
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_RRESP
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_RLAST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_RUSER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_RVALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXI_RREADY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXIS_TVALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXIS_TREADY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXIS_TDATA
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXIS_TSTRB
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXIS_TKEEP
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXIS_TLAST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXIS_TID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXIS_TDEST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/S_AXIS_TUSER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXIS_TVALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXIS_TREADY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXIS_TDATA
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXIS_TSTRB
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXIS_TKEEP
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXIS_TLAST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXIS_TID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXIS_TDEST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/M_AXIS_TUSER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AW_INJECTSBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AW_INJECTDBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AW_PROG_FULL_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AW_PROG_EMPTY_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AW_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AW_WR_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AW_RD_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AW_SBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AW_DBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AW_OVERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AW_UNDERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_W_INJECTSBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_W_INJECTDBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_W_PROG_FULL_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_W_PROG_EMPTY_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_W_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_W_WR_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_W_RD_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_W_SBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_W_DBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_W_OVERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_W_UNDERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_B_INJECTSBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_B_INJECTDBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_B_PROG_FULL_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_B_PROG_EMPTY_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_B_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_B_WR_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_B_RD_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_B_SBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_B_DBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_B_OVERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_B_UNDERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AR_INJECTSBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AR_INJECTDBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AR_PROG_FULL_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AR_PROG_EMPTY_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AR_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AR_WR_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AR_RD_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AR_SBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AR_DBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AR_OVERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_AR_UNDERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_R_INJECTSBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_R_INJECTDBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_R_PROG_FULL_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_R_PROG_EMPTY_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_R_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_R_WR_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_R_RD_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_R_SBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_R_DBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_R_OVERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXI_R_UNDERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXIS_INJECTSBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXIS_INJECTDBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXIS_PROG_FULL_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXIS_PROG_EMPTY_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXIS_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXIS_WR_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXIS_RD_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXIS_SBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXIS_DBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXIS_OVERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/AXIS_UNDERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/inverted_reset
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axis_din
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axis_dout
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axis_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axis_almost_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axis_prog_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axis_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axis_almost_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axis_prog_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axis_s_axis_tready
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axis_m_axis_tvalid
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axis_wr_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axis_rd_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wach_din
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wach_dout
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wach_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wach_almost_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wach_prog_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wach_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wach_almost_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wach_prog_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wdch_din
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wdch_dout
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wdch_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wdch_almost_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wdch_prog_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wdch_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wdch_almost_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wdch_prog_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wrch_din
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wrch_dout
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wrch_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wrch_almost_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wrch_prog_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wrch_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wrch_almost_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wrch_prog_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_aw_underflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_w_underflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_b_underflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_aw_overflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_w_overflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_b_overflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_wr_underflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_wr_overflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wach_s_axi_awready
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wach_m_axi_awvalid
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wach_wr_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wach_rd_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wdch_s_axi_wready
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wdch_m_axi_wvalid
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wdch_wr_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wdch_rd_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wrch_s_axi_bvalid
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wrch_m_axi_bready
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wrch_wr_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/wrch_rd_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rach_din
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rach_dout
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rach_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rach_almost_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rach_prog_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rach_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rach_almost_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rach_prog_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rdch_din
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rdch_dout
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rdch_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rdch_almost_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rdch_prog_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rdch_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rdch_almost_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rdch_prog_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_ar_underflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_r_underflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_ar_overflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_r_overflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_rd_underflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/axi_rd_overflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rach_s_axi_arready
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rach_m_axi_arvalid
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rach_wr_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rach_rd_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rdch_m_axi_rready
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rdch_s_axi_rvalid
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rdch_wr_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/rdch_rd_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/BACKUP
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/BACKUP_MARKER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/CLK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/SRST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_CLK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_RST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_CLK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_RST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DIN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_EN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_EN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_EMPTY_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_EMPTY_THRESH_ASSERT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_EMPTY_THRESH_NEGATE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_FULL_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_FULL_THRESH_ASSERT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_FULL_THRESH_NEGATE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/INT_CLK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/INJECTDBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/INJECTSBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DOUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/FULL
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/ALMOST_FULL
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_ACK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/OVERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/EMPTY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/ALMOST_EMPTY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/VALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/UNDERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_FULL
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_EMPTY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/SBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/srst_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_en_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_en_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/din_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/prog_empty_thresh_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/prog_empty_thresh_assert_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/prog_empty_thresh_negate_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/prog_full_thresh_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/prog_full_thresh_assert_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/prog_full_thresh_negate_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/injectdbiterr_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/injectsbiterr_delayed
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_asreg
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_asreg_d1
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_asreg_d2
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_reg
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_comb
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_d1
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_asreg
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_asreg_d1
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_asreg_d2
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_reg
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_comb
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_asreg
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_asreg_d1
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_asreg_d2
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_reg
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_comb
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_full_gen_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_full_ff_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_CLK_P0_IN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RST_P0_IN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_EN_FIFO_IN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_EN_P0_IN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/ALMOST_EMPTY_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/ALMOST_FULL_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DATA_COUNT_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DOUT_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/EMPTY_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/FULL_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/OVERFLOW_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_EMPTY_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_FULL_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/VALID_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_DATA_COUNT_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/UNDERFLOW_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_ACK_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_DATA_COUNT_FIFO_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DATA_P0_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/VALID_P0_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/EMPTY_P0_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/ALMOSTEMPTY_P0_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/EMPTY_P0_OUT_Q
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/ALMOSTEMPTY_P0_OUT_Q
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/UNDERFLOW_P0_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RDEN_P0_OUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DATA_P0_IN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/EMPTY_P0_IN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DATA_COUNT_FWFT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/SS_FWFT_WR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/SS_FWFT_RD
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/sbiterr_fifo_out
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/dbiterr_fifo_out
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/inject_sbit_err
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/inject_dbit_err
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_2_sync
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/clk_2_sync
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_d1
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_d2
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_d3
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_d4
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/find_log2/find_log2
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/find_log2/int_val
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/find_log2/i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/find_log2/j
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/DIN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/PROG_EMPTY_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/PROG_EMPTY_THRESH_ASSERT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/PROG_EMPTY_THRESH_NEGATE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/PROG_FULL_THRESH
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/PROG_FULL_THRESH_ASSERT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/PROG_FULL_THRESH_NEGATE
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/RD_CLK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/RD_EN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/RD_EN_USER
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/RST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/RST_FULL_GEN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/RST_FULL_FF
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/WR_RST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/RD_RST
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/WR_CLK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/WR_EN
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/INJECTDBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/INJECTSBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/USER_EMPTY_FB
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ALMOST_EMPTY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ALMOST_FULL
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/DOUT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/EMPTY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/FULL
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/OVERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/PROG_EMPTY
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/PROG_FULL
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/VALID
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/RD_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/UNDERFLOW
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/WR_ACK
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/WR_DATA_COUNT
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/SBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/DBITERR
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/rd_data_count_int
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/wr_data_count_int
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/wdc_fwft_ext_as
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/EXTRA_WORDS_DC
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/num_wr_bits
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/num_rd_bits
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/next_num_wr_bits
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/next_num_rd_bits
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/wr_ptr
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/wr_pntr
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/wr_pntr_rd1
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/wr_pntr_rd2
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/wr_pntr_rd3
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/adj_wr_pntr_rd
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/wr_pntr_rd
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/wr_rst_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/wr_rst_d1
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/rd_ptr
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/rd_pntr
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/rd_pntr_wr1
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/rd_pntr_wr2
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/rd_pntr_wr3
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/rd_pntr_wr4
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/adj_rd_pntr_wr
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/rd_pntr_wr
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/rd_rst_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ram_rd_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ram_rd_en_d1
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/empty_int
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/almost_empty_int
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ram_wr_en
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/full_int
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/almost_full_int
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/stage1_valid
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/stage2_valid
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/wr_ptr_rdclk
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/wr_ptr_rdclk_next
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/rd_ptr_wrclk
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/rd_ptr_wrclk_next
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/num_read_words_pe
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/num_write_words_pf
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/num_read_words_dc
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/num_read_words_sized_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/num_write_words_dc
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/num_write_words_sized_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ideal_dout_out
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/valid_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/valid_out
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/underflow_i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/err_type
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/err_type_d1
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ideal_dout
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ideal_dout_d1
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ideal_wr_ack
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ideal_valid
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ideal_overflow
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ideal_underflow
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ideal_prog_full
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ideal_prog_empty
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ideal_wr_count
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/ideal_rd_count
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/valid_d1
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/dout_reset_val
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/tmp_wr_listsize
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/tmp_rd_listsize
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/prog_empty_actual_thresh_assert
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/prog_empty_actual_thresh_negate
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/prog_full_actual_thresh_assert
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/prog_full_actual_thresh_negate
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/rdc_fwft_ext_as
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/diff_pntr
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/pf_thr_assert_val
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/pf_thr_negate_val
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/pe_thr_assert_val
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/pe_thr_negate_val
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/diff_pntr_rd
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/read_fifo/i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/read_fifo/tmp_dout
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/read_fifo/memory_read
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/read_fifo/tmp_rd_ptr
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/read_fifo/rd_ptr_high
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/read_fifo/rd_ptr_low
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/read_fifo/tmp_ecc_err
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/log2_val/log2_val
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/log2_val/binary_val
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/hexstr_conv/hexstr_conv
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/hexstr_conv/def_data
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/hexstr_conv/index
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/hexstr_conv/i
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/hexstr_conv/j
add wave -noupdate /encoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_as/hexstr_conv/bin
add wave -noupdate /encoder_top_tb/uut/bin2cw/clk
add wave -noupdate -color Magenta /encoder_top_tb/uut/bin2cw/bin_msg
add wave -noupdate /encoder_top_tb/uut/bin2cw/rst_b
add wave -noupdate /encoder_top_tb/uut/bin2cw/start
add wave -noupdate /encoder_top_tb/uut/bin2cw/fifoempty
add wave -noupdate /encoder_top_tb/uut/bin2cw/readfifo
add wave -noupdate -radix unsigned /encoder_top_tb/uut/bin2cw/cw_word
add wave -noupdate /encoder_top_tb/uut/bin2cw/ready
add wave -noupdate /encoder_top_tb/uut/bin2cw/done
add wave -noupdate /encoder_top_tb/uut/bin2cw/clr
add wave -noupdate /encoder_top_tb/uut/bin2cw/cnt
add wave -noupdate -itemcolor Magenta -radix unsigned /encoder_top_tb/uut/bin2cw/n
add wave -noupdate /encoder_top_tb/uut/bin2cw/n_sel
add wave -noupdate /encoder_top_tb/uut/bin2cw/n_rst
add wave -noupdate /encoder_top_tb/uut/bin2cw/delta_sel
add wave -noupdate /encoder_top_tb/uut/bin2cw/delta_rst
add wave -noupdate -itemcolor Magenta -radix unsigned /encoder_top_tb/uut/bin2cw/t
add wave -noupdate /encoder_top_tb/uut/bin2cw/t_sel
add wave -noupdate /encoder_top_tb/uut/bin2cw/t_rst
add wave -noupdate /encoder_top_tb/uut/bin2cw/rdy_sel
add wave -noupdate /encoder_top_tb/uut/bin2cw/done_sel
add wave -noupdate -itemcolor Magenta -radix unsigned /encoder_top_tb/uut/bin2cw/d
add wave -noupdate -itemcolor Magenta -radix unsigned /encoder_top_tb/uut/bin2cw/u
add wave -noupdate -color Gold -radix unsigned /encoder_top_tb/uut/bin2cw/state
add wave -noupdate /encoder_top_tb/uut/bin2cw/next_state
add wave -noupdate /encoder_top_tb/uut/bin2cw/read_one
add wave -noupdate /encoder_top_tb/uut/bin2cw/read_zero
add wave -noupdate -itemcolor Magenta -radix unsigned /encoder_top_tb/uut/bin2cw/i
add wave -noupdate /encoder_top_tb/uut/bin2cw/msg_buffer
add wave -noupdate /encoder_top_tb/uut/bin2cw/read1_update_delta
add wave -noupdate /encoder_top_tb/uut/bin2cw/read1_update_n
add wave -noupdate /encoder_top_tb/uut/bin2cw/read1_jmp_sel
add wave -noupdate /encoder_top_tb/uut/bin2cw/decodefd_done
add wave -noupdate /encoder_top_tb/uut/bin2cw/u_tmp
add wave -noupdate /encoder_top_tb/uut/bin2cw/read0_update_delta
add wave -noupdate /encoder_top_tb/uut/bin2cw/read0_update_n_part1
add wave -noupdate /encoder_top_tb/uut/bin2cw/read0_update_n_part2
add wave -noupdate /encoder_top_tb/uut/bin2cw/read0_update_t
add wave -noupdate /encoder_top_tb/uut/bin2cw/read0_jmp_sel
add wave -noupdate /encoder_top_tb/uut/bin2cw/left_shift
add wave -noupdate /encoder_top_tb/uut/bin2cw/shift_sel
add wave -noupdate /encoder_top_tb/uut/bin2cw/i_rst
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/clk
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/n
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/t
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/d
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/u
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/theta
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/p
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/multiplier/clk
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/multiplier/a
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/multiplier/b
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/multiplier/p
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/multiplier/sig00000001
add wave -noupdate /encoder_top_tb/uut/bin2cw/uut/multiplier/sig00000002
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {544852 ps} 0} {{Cursor 2} {4705225 ps} 0}
quietly wave cursor active 2
configure wave -namecolwidth 370
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {4659400 ps} {4758840 ps}
