######################################################################
##
## Filename: decoder_top_tb.udo
## Created on: Sun Jan 10 21:30:23 China Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
