######################################################################
##
## Filename: best_d_tb.udo
## Created on: Tue Dec 22 17:24:55 China Standard Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
