onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /decoder_top_tb/i
add wave -noupdate /decoder_top_tb/clk
add wave -noupdate /decoder_top_tb/rst_b
add wave -noupdate /decoder_top_tb/start
add wave -noupdate /decoder_top_tb/msg_bype
add wave -noupdate /decoder_top_tb/wr_en
add wave -noupdate /decoder_top_tb/bin_msg
add wave -noupdate /decoder_top_tb/msg_rdy
add wave -noupdate /decoder_top_tb/msg_done
add wave -noupdate /glbl/GSR
add wave -noupdate /decoder_top_tb/uut/clk
add wave -noupdate /decoder_top_tb/uut/rst_b
add wave -noupdate /decoder_top_tb/uut/start
add wave -noupdate /decoder_top_tb/uut/msg_bype
add wave -noupdate /decoder_top_tb/uut/wr_en
add wave -noupdate /decoder_top_tb/uut/bin_msg
add wave -noupdate /decoder_top_tb/uut/msg_rdy
add wave -noupdate /decoder_top_tb/uut/msg_done
add wave -noupdate /decoder_top_tb/uut/dout
add wave -noupdate /decoder_top_tb/uut/rd_en
add wave -noupdate /decoder_top_tb/uut/full
add wave -noupdate /decoder_top_tb/uut/empty
add wave -noupdate /decoder_top_tb/uut/data_count
add wave -noupdate /decoder_top_tb/uut/fifo/clk
add wave -noupdate /decoder_top_tb/uut/fifo/rst
add wave -noupdate /decoder_top_tb/uut/fifo/din
add wave -noupdate /decoder_top_tb/uut/fifo/wr_en
add wave -noupdate /decoder_top_tb/uut/fifo/rd_en
add wave -noupdate /decoder_top_tb/uut/fifo/dout
add wave -noupdate /decoder_top_tb/uut/fifo/full
add wave -noupdate /decoder_top_tb/uut/fifo/empty
add wave -noupdate /decoder_top_tb/uut/fifo/data_count
add wave -noupdate /decoder_top_tb/uut/fifo/inst/BACKUP
add wave -noupdate /decoder_top_tb/uut/fifo/inst/BACKUP_MARKER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/CLK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/RST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/SRST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/WR_CLK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/WR_RST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/RD_CLK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/RD_RST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/DIN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/WR_EN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/RD_EN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/PROG_EMPTY_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/PROG_EMPTY_THRESH_ASSERT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/PROG_EMPTY_THRESH_NEGATE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/PROG_FULL_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/PROG_FULL_THRESH_ASSERT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/PROG_FULL_THRESH_NEGATE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/INT_CLK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/INJECTDBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/INJECTSBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/DOUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/FULL
add wave -noupdate /decoder_top_tb/uut/fifo/inst/ALMOST_FULL
add wave -noupdate /decoder_top_tb/uut/fifo/inst/WR_ACK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/OVERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/EMPTY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/ALMOST_EMPTY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/VALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/UNDERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/RD_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/WR_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/PROG_FULL
add wave -noupdate /decoder_top_tb/uut/fifo/inst/PROG_EMPTY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/SBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/DBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_ACLK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_ACLK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_ARESETN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_ACLK_EN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_ACLK_EN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWADDR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWLEN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWSIZE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWBURST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWLOCK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWCACHE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWPROT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWQOS
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWREGION
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWUSER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWVALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_AWREADY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_WID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_WDATA
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_WSTRB
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_WLAST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_WUSER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_WVALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_WREADY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_BID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_BRESP
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_BUSER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_BVALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_BREADY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWADDR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWLEN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWSIZE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWBURST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWLOCK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWCACHE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWPROT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWQOS
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWREGION
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWUSER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWVALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_AWREADY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_WID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_WDATA
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_WSTRB
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_WLAST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_WUSER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_WVALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_WREADY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_BID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_BRESP
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_BUSER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_BVALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_BREADY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARADDR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARLEN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARSIZE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARBURST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARLOCK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARCACHE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARPROT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARQOS
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARREGION
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARUSER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARVALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_ARREADY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_RID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_RDATA
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_RRESP
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_RLAST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_RUSER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_RVALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXI_RREADY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARADDR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARLEN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARSIZE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARBURST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARLOCK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARCACHE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARPROT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARQOS
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARREGION
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARUSER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARVALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_ARREADY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_RID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_RDATA
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_RRESP
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_RLAST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_RUSER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_RVALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXI_RREADY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXIS_TVALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXIS_TREADY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXIS_TDATA
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXIS_TSTRB
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXIS_TKEEP
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXIS_TLAST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXIS_TID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXIS_TDEST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/S_AXIS_TUSER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXIS_TVALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXIS_TREADY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXIS_TDATA
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXIS_TSTRB
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXIS_TKEEP
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXIS_TLAST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXIS_TID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXIS_TDEST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/M_AXIS_TUSER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AW_INJECTSBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AW_INJECTDBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AW_PROG_FULL_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AW_PROG_EMPTY_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AW_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AW_WR_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AW_RD_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AW_SBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AW_DBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AW_OVERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AW_UNDERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_W_INJECTSBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_W_INJECTDBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_W_PROG_FULL_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_W_PROG_EMPTY_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_W_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_W_WR_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_W_RD_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_W_SBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_W_DBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_W_OVERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_W_UNDERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_B_INJECTSBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_B_INJECTDBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_B_PROG_FULL_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_B_PROG_EMPTY_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_B_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_B_WR_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_B_RD_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_B_SBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_B_DBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_B_OVERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_B_UNDERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AR_INJECTSBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AR_INJECTDBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AR_PROG_FULL_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AR_PROG_EMPTY_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AR_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AR_WR_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AR_RD_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AR_SBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AR_DBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AR_OVERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_AR_UNDERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_R_INJECTSBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_R_INJECTDBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_R_PROG_FULL_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_R_PROG_EMPTY_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_R_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_R_WR_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_R_RD_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_R_SBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_R_DBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_R_OVERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXI_R_UNDERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXIS_INJECTSBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXIS_INJECTDBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXIS_PROG_FULL_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXIS_PROG_EMPTY_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXIS_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXIS_WR_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXIS_RD_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXIS_SBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXIS_DBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXIS_OVERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/AXIS_UNDERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/inverted_reset
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axis_din
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axis_dout
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axis_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axis_almost_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axis_prog_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axis_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axis_almost_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axis_prog_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axis_s_axis_tready
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axis_m_axis_tvalid
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axis_wr_en
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axis_rd_en
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wach_din
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wach_dout
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wach_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wach_almost_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wach_prog_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wach_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wach_almost_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wach_prog_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wdch_din
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wdch_dout
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wdch_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wdch_almost_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wdch_prog_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wdch_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wdch_almost_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wdch_prog_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wrch_din
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wrch_dout
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wrch_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wrch_almost_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wrch_prog_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wrch_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wrch_almost_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wrch_prog_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_aw_underflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_w_underflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_b_underflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_aw_overflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_w_overflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_b_overflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_wr_underflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_wr_overflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wach_s_axi_awready
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wach_m_axi_awvalid
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wach_wr_en
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wach_rd_en
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wdch_s_axi_wready
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wdch_m_axi_wvalid
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wdch_wr_en
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wdch_rd_en
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wrch_s_axi_bvalid
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wrch_m_axi_bready
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wrch_wr_en
add wave -noupdate /decoder_top_tb/uut/fifo/inst/wrch_rd_en
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rach_din
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rach_dout
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rach_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rach_almost_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rach_prog_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rach_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rach_almost_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rach_prog_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rdch_din
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rdch_dout
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rdch_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rdch_almost_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rdch_prog_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rdch_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rdch_almost_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rdch_prog_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_ar_underflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_r_underflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_ar_overflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_r_overflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_rd_underflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/axi_rd_overflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rach_s_axi_arready
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rach_m_axi_arvalid
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rach_wr_en
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rach_rd_en
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rdch_m_axi_rready
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rdch_s_axi_rvalid
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rdch_wr_en
add wave -noupdate /decoder_top_tb/uut/fifo/inst/rdch_rd_en
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/BACKUP
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/BACKUP_MARKER
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/CLK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/SRST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_CLK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_RST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_CLK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_RST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DIN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_EN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_EN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_EMPTY_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_EMPTY_THRESH_ASSERT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_EMPTY_THRESH_NEGATE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_FULL_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_FULL_THRESH_ASSERT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_FULL_THRESH_NEGATE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/INT_CLK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/INJECTDBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/INJECTSBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DOUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/FULL
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/ALMOST_FULL
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_ACK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/OVERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/EMPTY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/ALMOST_EMPTY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/VALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/UNDERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_FULL
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_EMPTY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/SBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/srst_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_en_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_en_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/din_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/prog_empty_thresh_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/prog_empty_thresh_assert_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/prog_empty_thresh_negate_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/prog_full_thresh_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/prog_full_thresh_assert_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/prog_full_thresh_negate_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/injectdbiterr_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/injectsbiterr_delayed
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_asreg
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_asreg_d1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_asreg_d2
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_reg
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_comb
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_d1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_asreg
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_asreg_d1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_asreg_d2
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_reg
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_comb
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/wr_rst_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rd_rst_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_asreg
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_asreg_d1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_asreg_d2
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_reg
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_comb
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_full_gen_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_full_ff_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_CLK_P0_IN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RST_P0_IN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_EN_FIFO_IN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_EN_P0_IN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/ALMOST_EMPTY_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/ALMOST_FULL_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DATA_COUNT_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DOUT_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/EMPTY_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/FULL_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/OVERFLOW_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_EMPTY_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/PROG_FULL_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/VALID_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RD_DATA_COUNT_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/UNDERFLOW_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_ACK_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/WR_DATA_COUNT_FIFO_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DATA_P0_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/VALID_P0_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/EMPTY_P0_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/ALMOSTEMPTY_P0_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/EMPTY_P0_OUT_Q
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/ALMOSTEMPTY_P0_OUT_Q
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/UNDERFLOW_P0_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/RDEN_P0_OUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DATA_P0_IN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/EMPTY_P0_IN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/DATA_COUNT_FWFT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/SS_FWFT_WR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/SS_FWFT_RD
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/sbiterr_fifo_out
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/dbiterr_fifo_out
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/inject_sbit_err
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/inject_dbit_err
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_2_sync
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/clk_2_sync
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_d1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_d2
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_d3
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/rst_d4
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/find_log2/find_log2
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/find_log2/int_val
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/find_log2/i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/find_log2/j
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/CLK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/DIN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/PROG_EMPTY_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/PROG_EMPTY_THRESH_ASSERT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/PROG_EMPTY_THRESH_NEGATE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/PROG_FULL_THRESH
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/PROG_FULL_THRESH_ASSERT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/PROG_FULL_THRESH_NEGATE
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/RD_EN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/RST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/RST_FULL_GEN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/RST_FULL_FF
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/SRST
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/WR_EN
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/INJECTDBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/INJECTSBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ALMOST_EMPTY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ALMOST_FULL
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/DATA_COUNT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/DOUT
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/EMPTY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/FULL
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/OVERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/PROG_EMPTY
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/PROG_FULL
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/VALID
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/UNDERFLOW
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/WR_ACK
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/SBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/DBITERR
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/underflow_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/valid_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/valid_out
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/err_type
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/err_type_d1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ideal_dout
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ideal_dout_d1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ideal_dout_out
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/fwft_enabled
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ideal_wr_ack
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ideal_valid
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ideal_overflow
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ideal_underflow
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/full_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/empty_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/almost_full_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/almost_empty_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/prog_full_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/prog_empty_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/wr_pntr
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/rd_pntr
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/diff_count
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/write_allow_q
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/read_allow_q
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/valid_d1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/rst_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/srst_i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/dout_reset_val
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ram_rd_en_d1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/srst_i_d1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/srst_i_d2
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/write_allow
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/read_allow
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/write_only
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/write_only_q
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/read_only
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/read_only_q
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/diff_pntr
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/diff_pntr_pe
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/dout_tmp_q
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/dout_tmp
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/dout_tmp1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/comp1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/comp0
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/going_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/leaving_full
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ram_full_comb
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ecomp1
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ecomp0
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/going_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/leaving_empty
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/ram_empty_comb
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/pf3_assert_val
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/pf_assert_val
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/pf_negate_val
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/pe3_assert_val
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/pe4_assert_val
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/pe4_negate_val
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/log2_val/log2_val
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/log2_val/binary_val
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/hexstr_conv/hexstr_conv
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/hexstr_conv/def_data
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/hexstr_conv/index
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/hexstr_conv/i
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/hexstr_conv/j
add wave -noupdate /decoder_top_tb/uut/fifo/inst/conv_fifo/fifo_generator_v8_2_conv_dut/block1/gen_ss/hexstr_conv/bin
add wave -noupdate /decoder_top_tb/uut/cw2bin/clk
add wave -noupdate /decoder_top_tb/uut/cw2bin/cw_word
add wave -noupdate /decoder_top_tb/uut/cw2bin/rst_b
add wave -noupdate /decoder_top_tb/uut/cw2bin/start
add wave -noupdate /decoder_top_tb/uut/cw2bin/fifoempty
add wave -noupdate /decoder_top_tb/uut/cw2bin/readfifo
add wave -noupdate -color Magenta /decoder_top_tb/uut/cw2bin/bin_msg
add wave -noupdate -color Magenta /decoder_top_tb/uut/cw2bin/ready
add wave -noupdate /decoder_top_tb/uut/cw2bin/done
add wave -noupdate /decoder_top_tb/uut/cw2bin/clr
add wave -noupdate /decoder_top_tb/uut/cw2bin/cnt
add wave -noupdate -color Magenta -itemcolor {Green Yellow} -radix unsigned /decoder_top_tb/uut/cw2bin/n
add wave -noupdate /decoder_top_tb/uut/cw2bin/n_sel
add wave -noupdate /decoder_top_tb/uut/cw2bin/n_rst
add wave -noupdate -radix unsigned /decoder_top_tb/uut/cw2bin/delta
add wave -noupdate /decoder_top_tb/uut/cw2bin/delta_sel
add wave -noupdate /decoder_top_tb/uut/cw2bin/delta_rst
add wave -noupdate -color Magenta -itemcolor {Green Yellow} -radix unsigned /decoder_top_tb/uut/cw2bin/t
add wave -noupdate /decoder_top_tb/uut/cw2bin/t_sel
add wave -noupdate /decoder_top_tb/uut/cw2bin/t_rst
add wave -noupdate /decoder_top_tb/uut/cw2bin/rdy_sel
add wave -noupdate /decoder_top_tb/uut/cw2bin/done_sel
add wave -noupdate -radix unsigned /decoder_top_tb/uut/cw2bin/d
add wave -noupdate -radix unsigned /decoder_top_tb/uut/cw2bin/u
add wave -noupdate -color Gold -radix unsigned /decoder_top_tb/uut/cw2bin/state
add wave -noupdate /decoder_top_tb/uut/cw2bin/next_state
add wave -noupdate /decoder_top_tb/uut/cw2bin/read_geq
add wave -noupdate /decoder_top_tb/uut/cw2bin/read_lt
add wave -noupdate /decoder_top_tb/uut/cw2bin/geq_done
add wave -noupdate /decoder_top_tb/uut/cw2bin/lt_done
add wave -noupdate -radix unsigned /decoder_top_tb/uut/cw2bin/msg_sel
add wave -noupdate -radix binary -childformat {{{/decoder_top_tb/uut/cw2bin/i[14]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[13]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[12]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[11]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[10]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[9]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[8]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[7]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[6]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[5]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[4]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[3]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[2]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[1]} -radix unsigned} {{/decoder_top_tb/uut/cw2bin/i[0]} -radix unsigned}} -subitemconfig {{/decoder_top_tb/uut/cw2bin/i[14]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[13]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[12]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[11]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[10]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[9]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[8]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[7]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[6]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[5]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[4]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[3]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[2]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[1]} {-height 15 -radix unsigned} {/decoder_top_tb/uut/cw2bin/i[0]} {-height 15 -radix unsigned}} /decoder_top_tb/uut/cw2bin/i
add wave -noupdate /decoder_top_tb/uut/cw2bin/geq_update_delta
add wave -noupdate /decoder_top_tb/uut/cw2bin/geq_update_n
add wave -noupdate /decoder_top_tb/uut/cw2bin/lt_update_delta
add wave -noupdate /decoder_top_tb/uut/cw2bin/lt_update_n_part1
add wave -noupdate /decoder_top_tb/uut/cw2bin/lt_update_n_part2
add wave -noupdate /decoder_top_tb/uut/cw2bin/lt_update_t
add wave -noupdate /decoder_top_tb/uut/cw2bin/left_shift
add wave -noupdate /decoder_top_tb/uut/cw2bin/shift_sel
add wave -noupdate /decoder_top_tb/uut/cw2bin/i_rst
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/clk
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/n
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/t
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/d
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/u
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/theta
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/p
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/multiplier/clk
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/multiplier/a
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/multiplier/b
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/multiplier/p
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/multiplier/sig00000001
add wave -noupdate /decoder_top_tb/uut/cw2bin/uut/multiplier/sig00000002
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 2} {524851 ps} 0} {{Cursor 3} {2345004 ps} 0}
quietly wave cursor active 2
configure wave -namecolwidth 450
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {2293577 ps} {2382665 ps}
