######################################################################
##
## Filename: encoder_top.udo
## Created on: Wed Jan 13 17:47:20 China Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
