######################################################################
##
## Filename: encoder_top_tb.udo
## Created on: Thu Jan 07 10:33:39 China Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
