######################################################################
##
## Filename: encoder_top_tb.udo
## Created on: Wed Jan 06 22:15:45 China Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
