######################################################################
##
## Filename: decoder_top_tb.udo
## Created on: Fri Jan 08 14:32:31 China Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
