######################################################################
##
## Filename: encryptor_top_tb.udo
## Created on: Sun Jan 17 16:50:33 China Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
